version: '1'
services:
  differential-gps-manager-backend:
    image: 'differential-gps-manager-backend:v1'
    networks:
      - jobnetwork
    container_name: differential-gps-manager-backend
    restart: always
    ports:
      - 8091:8091
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2000M
        reservations:
          cpus: "0.5"
          memory: 2000M
    environment:
      - JAVA_OPTS=-server -Xms2000m -Xmx2000m -XX:CompressedClassSpaceSize=128m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2
networks:
  jobnetwork:
    driver: bridge
